version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6543:6543"
    networks:
      - backend-network

  backend-blashape:
    build: .
    container_name: backend-blashape
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_MAIL_USERNAME=${ORG_EMAIL}
      - SPRING_MAIL_PASSWORD=${ORG_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
