version: "3.9"

services:
  backend-blashape:
    image: leviwzz/backend-blashape:latest
    container_name: backend-blashape
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPRING_MAIL_USERNAME=${ORG_EMAIL}
      - SPRING_MAIL_PASSWORD=${ORG_PASSWORD}
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
